### ISSUE TITLE
PUT operation must change

### ISSUE THREAD

**Issue by ysriram** [FlatBallFlyer/IBM-Data-Merge-Utility#15]
`PUT /template/templateFullName `must change to `PUT /templates/:collection` the reason are as follows.

- The JSON payload is completely self describing in the sense that it has the  `name`, and `columnValue` (if any).

- The `name`, and `columnValue` can be mutated in the UI hence a new template in the server must be created under the `:collection` and the UI needs to be refreshed .. etc.

- And we can completely avoid the `dot` notation in the URI

**Comment by jonathanIBM** [comment]
Implemented as of 964ae15afc80bc483934b7c5b5f69dd2db2bc45e
