### ISSUE TITLE
Backend API - Save template generates a new collection name

### ISSUE THREAD

**Issue by ysriram** [FlatBallFlyer/IBM-Data-Merge-Utility#19]
Steps to repro.

- Edit any template example contact.cmd
- Add some description or something
- Save

Result

- A new collection is created as contact.cmd.

Expected

- No new collection should be created
- contact.cmd template must be saved with new description

**Comment by FlatBallFlyer** [comment]
Yeah, can you validate the URL you are using, the documentation inicates 
PUT    /idmu/templates/{collectionName} with the template template JSON
So the rest call should be PUT /idmu/templates/YourCollection?[TemplateJson] - if you are calling with the template full name (i.e. PUT /idmu/templates/YourCollection.YourName.?[TemplateJson] then you would get the new collection "YourColleciton.YourName."

**Comment by FlatBallFlyer** [comment]
Corrected in latest rest api
