### ISSUE TITLE
Implement properties files based JDBC connection abstraction

### ISSUE THREAD

**Issue by FlatBallFlyer** [FlatBallFlyer/IBM-Data-Merge-Utility#2]
Implement a non JNDI based connection pooling class that can be used in the MergeContext.getConnection method in place of JNDI lookup.

**Comment by jonathanIBM** [comment]
We should move away from writing our own connection pool and use an existing one instead. This will be part of and scope limited to the hibernate persistence support

**Comment by FlatBallFlyer** [comment]
Keep in mind that the ConnectionFactory (or Connection) is used by the JDBC Data provider, so the scope of it's use is beyond what Hibernate will be touching. The role of the Connection class will just be a wrapper for the connection that is a "lazy loader" (i.e. it's not connected till it's actually needed by a directive)

**Comment by FlatBallFlyer** [comment]
We should also implement your suggestions on abstraction of the JDBC connection out of Context.xml, and possibly expose a service to configure a data source. This work also needs to include an abstraction of getting JDBC connection credentials. Requirements and details will be forthcoming. This credential function is a candidate for the dedicated branch we discussed that may also include the Hibernate code.

**Comment by FlatBallFlyer** [comment]
Updates on the abstraction layer for JDBC connection credentials. We need to implement optional support for CyberArc authentication, details here: http://www.cyberark.com

**Comment by FlatBallFlyer** [comment]
Work remains here, I was unable to follow the connection abstraction implemented in the latest commits of the related code in ConnectionFactory, and SqlProvider. I have attempted to show some of the changes I expect to be needed in RuntimeContext (Lazy Loaded connections hash) but additional changes are needed to SqlProvider to utilize the lazy-loaded connection and utilize the ConnectionPool mechanism introduced post Beta b1g.

**Comment by FlatBallFlyer** [comment]
Complete
