### ISSUE TITLE
Backend API - Add New Template [PUT]

### ISSUE THREAD

**Issue by ysriram** [FlatBallFlyer/IBM-Data-Merge-Utility#20]
Unable to create a new template using example below. 
```
PUT /template/yesh.cmd.
{
  collection: "yesh",
  name: "cmd"
}
```

**Comment by FlatBallFlyer** [comment]
Are you getting an error message?

**Comment by FlatBallFlyer** [comment]
I think this is a problem with the format of your put call.... according to the API doc in the readme 
PUT    /idmu/templates/{collectionName} with the template JSON
So the put should be /idmu/templates/yesh?[json template]
Please validate using this syntax.

**Comment by ysriram** [comment]
Works well now with /templates instead of the /template which was part of the original documentation.
