### ISSUE TITLE
Proposed - Admin Guide Table of Contents

### ISSUE THREAD

**Issue by darrenshoch** [FlatBallFlyer/IBM-Data-Merge-Utility#45]
* Licensing
* Dependencies
* Overview
* Installing
    * Quick Install
    * Enterprise Deployment Architecture
        * Change Management
        * High Availability Options
        * Scaling of Options
* Administrating
    * Development Install
    * Production Install
    * Securing the server
    * Housekeeping of Merge Output / Logs
    * Backup / Restore guidelines
    * Configuration Options
        * Configuring JDBC Data Sources
        * Template Persistence Options
            * Configure File System Persistence
            * Configure Database Persistence
        * Merge Output Directory
        * Default Package Name
        * json "pretty" formatting
        * Logging

**Comment by FlatBallFlyer** [comment]
approved

**Comment by darrenshoch** [comment]
For these new sections, are you providing the source content for the "Administering" section?
