### ISSUE TITLE
Proposed - User Guide

### ISSUE THREAD

**Issue by darrenshoch** [FlatBallFlyer/IBM-Data-Merge-Utility#46]
This is the final TOC for the User Guide. 
Items noted with ** will be "Coming Soon" and content is deferred 
* Licensing
* Calling the Merge Servlet
* The Replace Hash
* Inserting Sub-Templates
* Reserved Words
* The Template Editor
    * Collections
    * Adding a Template
    * Saving a Template
    * Editing a Template
    * Removing a Template
    * Adding Directives
    * Editing Directives
    * Inserting Sub-templates and Bookmarks
* Output Files
* Directives Matrix (New)
* Directives (Just summary definition, no code)
    * Require
    * Replace Value
    * Insert Sub-Templates from Tag
    * Insert Sub-Templates from Sql Rows
    * Get Replace Values From Sql Row
    * Get Replace Values From Sql Column
    * Insert Sub-Templates from Csv Rows
    * Get Replace Values From Csv Row
    * Get Replace Values From Csv Column
    * Insert Sub-Templates from Html Table Rows**
    * Get Replace Values From Html Table Row**
    * Get Replace Values From Html Table Column**
    * Get Replace Values From Html Markup**
* Providers
    * JDBC Data
    * CSV Data
    * HTML Data**
    * Tag Data

**Comment by FlatBallFlyer** [comment]
Approved final
