### ISSUE TITLE
Insert Sub fails to create sub-template

### ISSUE THREAD

**Issue by FlatBallFlyer** [FlatBallFlyer/IBM-Data-Merge-Utility#50]
The Insert Sub-template action creates the bookmark but fails to create the underlying template.

**Comment by ysriram** [comment]
Creates sub-template using the collection, and name properties of the bookmark. Example call used is below. Only on success the bookmark is inserted into the text-area. All other actions remains same.

```
PUT /idmu/template
{
  "collection": "dish",
  "name": "cmd",
  "columnValue": "",
  "description": "",
  "outputFile": "",
  "content": "",
  "directives": []
}
```
