### ISSUE TITLE
Input for HTTP directive default data must allow embedded newlines and tabs

### ISSUE THREAD

**Issue by FlatBallFlyer** [FlatBallFlyer/IBM-Data-Merge-Utility#52]
The input for the "Default Data" of the HTTP based directives (CSV/HTML) must support embedded newlines and tabs (i.e. this will be a textarea not a "input" area.)

**Comment by ysriram** [comment]
Only the 'provider.staticData' for all CSV/HTML directives has been changed to textarea.
