### ISSUE TITLE
Template Content textarea not self-sizing

### ISSUE THREAD

**Issue by FlatBallFlyer** [FlatBallFlyer/IBM-Data-Merge-Utility#54]
This is a regression defect, the text area for Template Content is no longer vertically sizing itself. It should default to the number of lines in the text area when rendered, and a single line if the text area is empty and should automatically resize itself as new text is added or removed.

**Comment by ysriram** [comment]
Not possible.

**Comment by ysriram** [comment]
Content area will now expand as you type or when a bookmark is pasted.
