### ISSUE TITLE
Require Tags directive editor uses invalid JSON for tags field

### ISSUE THREAD

**Issue by FlatBallFlyer** [FlatBallFlyer/IBM-Data-Merge-Utility#59]
The tags field should be presented as a coma-sperated list of strings, and json encoded as a list of string.  i.e. The tags input field with a value of "A,b,C" should be json encoded as ["A","b","C"] and visa-versa, as in the documentation: 

"tags": ["Foo","empty"]

**Comment by ysriram** [comment]
Fixed in branch 'yesh-bug-fixes' https://github.com/FlatBallFlyer/IBM-Data-Merge-Utility/commit/7cba0ad87a2fdd98231772ac331dc0be60e0f4d7
