### ISSUE TITLE
All Insert-Subs directive editors produce invalid JSON for Not-Last/Only-Last fields

### ISSUE THREAD

**Issue by FlatBallFlyer** [FlatBallFlyer/IBM-Data-Merge-Utility#60]
The Not Last and Only Last fields should be presented as a coma-sperated list of strings, and json encoded as a list of string.  i.e. The not last input field with a value of "COMA,SEMI" should be json encoded as ["COMA","SEMI"], the value "empty" should be ["empty"] and a empty value should be absent or have the form [], as in the documentation: 

"notLast": ["empty"],
"onlyLast": [],

**Comment by ysriram** [comment]
Fixed in branch 'yesh-bug-fixes' https://github.com/FlatBallFlyer/IBM-Data-Merge-Utility/commit/7cba0ad87a2fdd98231772ac331dc0be60e0f4d7
