### ISSUE TITLE
The Replace Value directive editor is non-functional

### ISSUE THREAD

**Issue by FlatBallFlyer** [FlatBallFlyer/IBM-Data-Merge-Utility#61]
Description does not update in the Directives List.
Changes are lost if you go “back” and re-enter editor
Changes are lost if you edit another directive in the list
Changes do not save (are not present in the rest call)

**Comment by ysriram** [comment]
Fixed in branch 'yesh-bug-fixes' https://github.com/FlatBallFlyer/IBM-Data-Merge-Utility/commit/7cba0ad87a2fdd98231772ac331dc0be60e0f4d7
